/**
 * Product catalog constants.
 */

const MAX_QUERY_LIMIT = 50;
const DEFAULT_QUERY_LIMIT = 20;
const DEFAULT_SUGGESTION_LIMIT = 8;
const MAX_SUGGESTION_LIMIT = 20;
const CATALOG_NAMESPACE = 'catalog';
const DEFAULT_CATALOG_CACHE_TTL_MS = Number.parseInt(
  process.env.PRODUCT_CATALOG_CACHE_TTL_MS || '120000',
  10
);
const DEFAULT_SUGGESTION_CACHE_TTL_MS = Number.parseInt(
  process.env.PRODUCT_SUGGESTION_CACHE_TTL_MS || '45000',
  10
);
const SEARCH_SUGGESTION_ENABLE_SEMANTIC_FALLBACK = String(
  process.env.PRODUCT_SUGGESTION_ENABLE_SEMANTIC_FALLBACK || 'true'
).toLowerCase() === 'true';
const RELEVANCE_CANDIDATE_MULTIPLIER = Number.parseInt(
  process.env.PRODUCT_RELEVANCE_CANDIDATE_MULTIPLIER || '6',
  10
);
const RELEVANCE_MIN_CANDIDATES = Number.parseInt(
  process.env.PRODUCT_RELEVANCE_MIN_CANDIDATES || '40',
  10
);
const RELEVANCE_MAX_CANDIDATES = Number.parseInt(
  process.env.PRODUCT_RELEVANCE_MAX_CANDIDATES || '300',
  10
);
const RELEVANCE_LEXICAL_WEAK_THRESHOLD = Number.parseInt(
  process.env.PRODUCT_RELEVANCE_LEXICAL_WEAK_THRESHOLD || '4',
  10
);

module.exports = {
  CATALOG_NAMESPACE,
  DEFAULT_CATALOG_CACHE_TTL_MS,
  DEFAULT_QUERY_LIMIT,
  DEFAULT_SUGGESTION_CACHE_TTL_MS,
  DEFAULT_SUGGESTION_LIMIT,
  MAX_QUERY_LIMIT,
  MAX_SUGGESTION_LIMIT,
  RELEVANCE_CANDIDATE_MULTIPLIER,
  RELEVANCE_LEXICAL_WEAK_THRESHOLD,
  RELEVANCE_MAX_CANDIDATES,
  RELEVANCE_MIN_CANDIDATES,
  SEARCH_SUGGESTION_ENABLE_SEMANTIC_FALLBACK,
};
